repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.10.0
    hooks:
      - id: black
        args: [--preview]

  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0
    hooks:
      - id: reorder-python-imports
