name: Lint

on: [push, pull_request, workflow_dispatch]

env:
  FORCE_COLOR: 1
  PRE_COMMIT_COLOR: always

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: hynek/setup-cached-uv@v2
      - name: pre-commit
        run: uv run --with pre-commit-uv pre-commit run --show-diff-on-failure

  mypy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: hynek/setup-cached-uv@v2
      - name: Mypy
        run: uvx --with tox-uv tox -e mypy
